interface QuestionData {
  link: string;
  title: string;
  description: string;
  compiledPdf: string;    
  templateFile: string;       
  atsFriendly: boolean;
  atsNotes: string;
  preferredBy: string[];
}

const resumeTemplates: Record<string, QuestionData[]> = {
  templates: [
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574499/resume1_auxazk.jpg",
      title: "Modern Resume",
      description: "A sleek and contemporary resume template designed for technology professionals, emphasizing clarity and readability.",
      compiledPdf: "",
      templateFile: "modernResume.html",
      atsFriendly: true,
      atsNotes: "Simple structure, easy for ATS parsing",
      preferredBy: ["Tech professionals", "Developers"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574499/resume2_qlqa1i.jpg",
      title: "Classic Resume",
      description: "A timeless and structured resume template with a traditional layout, ideal for corporate and formal applications.",
      compiledPdf: "",
      templateFile: "classicResume.html",
      atsFriendly: true,
      atsNotes: "Standard layout, compatible with most ATS",
      preferredBy: ["Corporate", "HR professionals"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574500/resume3_xqjrcb.jpg",
      title: "Creative Resume",
      description: "A visually engaging resume template with creative design elements, perfect for creative professionals seeking to stand out.",
      compiledPdf: "",
      templateFile: "creativeResume.html",
      atsFriendly: true,
      atsNotes: "May not parse well in some ATS systems due to design",
      preferredBy: ["Designers", "Creative professionals"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574500/resume4_nm6mxq.jpg",
      title: "Professional Resume",
      description: "A clean and organized resume template that highlights professional experience and skills in a structured manner.",
      compiledPdf: "",
      templateFile: "professionalResume.html",
      atsFriendly: true,
      atsNotes: "Clean sections, easy for ATS to scan",
      preferredBy: ["Business", "Management"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574499/resume5_lnyyb9.jpg",
      title: "Minimalist Resume",
      description: "A minimalist resume template focused on essential information, delivering simplicity without compromising professionalism.",
      compiledPdf: "",
      templateFile: "minimalistResume.html",
      atsFriendly: true,
      atsNotes: "Simple and readable format for ATS",
      preferredBy: ["Startups", "Freelancers"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574496/resume6_m0hgil.jpg",
      title: "Elegant Resume",
      description: "An elegant resume template that combines refined visual elements with professional formatting for a polished presentation.",
      compiledPdf: "",
      templateFile: "elegantResume.html",
      atsFriendly: true,
      atsNotes: "Visual elements may interfere with ATS parsing",
      preferredBy: ["Executives", "Professionals seeking elegance"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574498/resume7_ect2ba.jpg",
      title: "Bold Resume",
      description: "A bold and striking resume template with impactful design, ideal for making a strong impression in creative industries.",
      compiledPdf: "",
      templateFile: "boldResume.html",
      atsFriendly: true,
      atsNotes: "Bold formatting may confuse ATS systems",
      preferredBy: ["Creative professionals", "Marketers"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574495/resume8_foljw5.jpg",
      title: "Simple Resume",
      description: "A straightforward and functional resume template that emphasizes essential details and clarity for all professional applications.",
      compiledPdf: "",
      templateFile: "simple.html",
      atsFriendly: true,
      atsNotes: "Clear and simple structure ideal for ATS",
      preferredBy: ["All professionals"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574495/resume9_wimfpo.jpg",
      title: "Modern Minimalist Resume",
      description: "A modern minimalist resume template that balances contemporary style with simplicity, ensuring easy readability and professionalism.",
      compiledPdf: "",
      templateFile: "modernMinimalist.html",
      atsFriendly: true,
      atsNotes: "Minimal design helps ATS readability",
      preferredBy: ["Tech", "Startups"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574495/resume10_rsp6mp.jpg",
      title: "Clean Resume",
      description: "A clean and highly readable resume template designed for clarity, highlighting skills and experience without unnecessary clutter.",
      templateFile: "cleanResume.html",
      compiledPdf: "",
      atsFriendly: true,
      atsNotes: "Readable and ATS-friendly layout",
      preferredBy: ["Corporate", "Developers"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574495/resume11_p3feba.jpg",
      title: "Classic Professional Resume",
      description: "A classical professional resume template combining traditional structure with an organized layout for effective presentation.",
      compiledPdf: "",
      templateFile: "professional.html",
      atsFriendly: true,
      atsNotes: "Formal structure, ATS-friendly",
      preferredBy: ["Corporate", "HR"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574495/resume12_vr7eej.jpg",
      title: "Creative Modern Resume",
      description: "A modern resume with creative touches that enhances visual appeal while maintaining professional clarity.",
      compiledPdf: "",
      templateFile: "creativemodern.html",
      atsFriendly: true,
      atsNotes: "Visual design may interfere with ATS",
      preferredBy: ["Designers", "Creative roles"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574495/resume13_xluqq1.jpg",
      title: "Elegant Minimal Resume",
      description: "An elegant, minimal resume template providing a professional yet refined presentation for formal applications.",
      compiledPdf: "",
      templateFile: "elegant.html",
      atsFriendly: true,
      atsNotes: "Minimalistic design, ATS-friendly",
      preferredBy: ["Executives", "Professionals"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756575824/resume14_orkrg5.jpg",
      title: "Professional Clean Resume",
      description: "A clean and professional resume layout designed to clearly present skills and experience with a polished look.",
      compiledPdf: "",
      templateFile: "professionalClearn.html",
      atsFriendly: true,
      atsNotes: "Readable, ATS-friendly format",
      preferredBy: ["Corporate", "Business professionals"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574705/resume15_evwss7.jpg",
      title: "Modern Sleek Resume",
      description: "A sleek, contemporary resume template with a modern aesthetic, highlighting professional achievements efficiently.",
      compiledPdf: "",
      templateFile: "modernSleek.html",
      atsFriendly: true,
      atsNotes: "Simple and modern layout suitable for ATS",
      preferredBy: ["Tech", "Startups"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574695/resume16_kbphx1.jpg",
      title: "Simple Professional Resume",
      description: "A straightforward professional resume designed to present qualifications and experience clearly and concisely.",
      compiledPdf: "",
      templateFile: "simpleProfessional.html",
      atsFriendly: true,
      atsNotes: "Clear and readable for ATS systems",
      preferredBy: ["Corporate", "General professionals"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574694/resume17_qchtr9.jpg",
      title: "Bold Creative Resume",
      description: "A bold resume with creative layout and impactful sections to help applicants stand out in competitive creative industries.",
      compiledPdf: "",
      templateFile: "boldCreativeResume.html",
      atsFriendly: true,
      atsNotes: "Creative layout may reduce ATS readability",
      preferredBy: ["Designers", "Marketers"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574693/resume18_nxbf7p.jpg",
      title: "Minimalist Clean Resume",
      description: "A minimalist and clean resume design focusing on essential content for a professional and modern presentation.",
      compiledPdf: "",
      templateFile: "minimalistCleanResume.html",
      atsFriendly: true,
      atsNotes: "Minimal layout ensures ATS compatibility",
      preferredBy: ["Tech", "Startups"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574694/resume19_pobqg5.jpg",
      title: "Creative Professional Resume",
      description: "A creative resume template that balances professional content with visually engaging design elements.",
      compiledPdf: "",
      templateFile: "creativeProfessional.html",
      atsFriendly: true,
      atsNotes: "Visual design may limit ATS parsing",
      preferredBy: ["Creative professionals", "Marketing"],
    },
    {
      link: "https://res.cloudinary.com/dsj6bnrvz/image/upload/v1756574693/resume20_ftu6xu.jpg",
      title: "Classic Clean Resume",
      description: "A clean and classic resume template with a professional structure, ideal for corporate and formal applications.",
      compiledPdf: "",
      templateFile: "classicCleanResume.html",
      atsFriendly: true,
      atsNotes: "Simple, structured, ATS-friendly",
      preferredBy: ["Corporate", "Business"],
    },
  ],
};

export default resumeTemplates;